stages:
    - build

build:
    stage: build
    script: 
        - apt-get update && apt-get install -y dh-autoreconf
        - autoreconf --install
        - autoconf && aclocal && sh autogen.sh && sh configure
        - make && make install
