stages:
    - build

build:
    stage: build
    script: 
        - apt-get update && apt-get install -y dh-autoreconf
        - autoreconf --install
        - autoconf && aclocal && sh autogen.sh && sh configure
        - make && make install && make install-strip
    artifacts:
        name: "$CI_JOB_NAME"
        untracked: true
        expire_in: 1 day
