#!/bin/bash

# In global configuration register, disable I2C watchdog
./i2c_bb -s 0x20 -l 1 -i 0x0 0x20

# For Fan 1, set the target PWM duty cycle as needed (set to 59%)
./i2c_bb -s 0x20 -l 1 -i 0x40 0x96
./i2c_bb -s 0x20 -l 1 -i 0x41 0x00

# For Fan 2, set the target PWM duty cycle as needed (set to 59%)
./i2c_bb -s 0x20 -l 1 -i 0x42 0x96
./i2c_bb -s 0x20 -l 1 -i 0x43 0x00

# For Fan 3, set the target PWM duty cycle as needed (set to 59%)
./i2c_bb -s 0x20 -l 1 -i 0x44 0x96
./i2c_bb -s 0x20 -l 1 -i 0x45 0x00

# For Fan 4, set the target PWM duty cycle as needed (set to 59%)
./i2c_bb -s 0x20 -l 1 -i 0x46 0x96
./i2c_bb -s 0x20 -l 1 -i 0x47 0x00

# For Fan 5, set the target PWM duty cycle as needed (set to 59%)
./i2c_bb -s 0x20 -l 1 -i 0x48 0x96
./i2c_bb -s 0x20 -l 1 -i 0x49 0x00

# For Fan 6, set the target PWM duty cycle as needed (set to 59%)
./i2c_bb -s 0x20 -l 1 -i 0x4a 0x96
./i2c_bb -s 0x20 -l 1 -i 0x4b 0x00

